name: API Automation Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  run-automation-test:
    runs-on: ubuntu-latest

    steps:
    # download repo    
    - uses: actions/checkout@v3
    
    # setup java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    # setup gradlew
    - name: Setup gradlew
      run: chmod +x gradlew
    
    # execute gradle command for running testng test
    - name: Execute Test
      run: ./gradlew clean test
    
    # archive test result
    - name: Archive Test Result
      uses: actions/upload-artifact@v3.1.2
      if: always()
      with:
        name: TestNG Report
        path: reports
    
    # deploy to github pages
    - name: Deploy report to github pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        personal_token: ${{ secrets.TOKEN }}
        publish_dir: reports
